### ISSUE TITLE
http error 503

### ISSUE THREAD

**Issue by Amsori** [binary-com/websockets#35] opened 2015-11-23 02:28 UTC
we have foound problem every connect to websocket binary server. we found connection error and have message 503 error http connection. we was try 100x and have 95% found same problem.
please fix.

**Comment by raunakkathuria** [comment] 2015-11-23 02:49
@Amsori just want to add that we have rate limit in place i.e. when you retry connection too fast to our server you will get HTTP 503, we have rate limit that only allows connection initiation rate at 1req/sec/IP address

**Comment by Amsori** [comment] 2015-11-23 02:51
we only connect 1 connection but still found that. so what must i do ?

**Comment by raunakkathuria** [comment] 2015-11-23 02:55
@Amsori so just want to confirm, so whenever you send request you open a new connection or you use the same connection that is already initiated, can you also perform a `ping -c10 www.binary.com` and `traceroute www.binary.com` using shell

**Comment by Amsori** [comment] 2015-11-23 03:11
how ever about the share connection. in indonesia 1 IP perhaps use many
people ?

**Comment by raunakkathuria** [comment] 2015-11-23 03:14
if that IP has many ws connection then yes it will be blocked and allow only one connection

**Comment by Amsori** [comment] 2015-11-23 03:19
ooooh... this is the new problem... from my country 1 IP usuale used many people. because this connection shared like speedy internet connection. if you blocked IP, many people will cannot using binary. so you must find new solution.

**Comment by raunakkathuria** [comment] 2015-11-23 03:28
@Amsori so that means on same IP, we have lots of binary.com website open? if yes so it will be blocked and only one connection will be allowed.

**Comment by Amsori** [comment] 2015-11-23 03:33
yes,
for example. we use public IP and Nat to local network.
Public IP is 36.74.24.123
and we shared to local network / LAN.
we have 25 client network and all client open binary.com
so, if this happens then if this would be blocked ?

**Comment by davebond** [comment] 2015-11-23 17:11
I'm also having this issue and I am the only one using this IP

**Comment by Amsori** [comment] 2015-11-23 23:32
How to solve it. Please share your solutions

**Comment by davebond** [comment] 2015-11-24 01:17
A full dump from CURL

```text
curl -v -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: www.binary.com" -H "Origin: https://www.binary.com" https://www.binary.com/websockets/v3
* Hostname was NOT found in DNS cache
*   Trying 104.20.83.128...
* Connected to www.binary.com (104.20.83.128) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl318606.cloudflaressl.com
* 	 start date: 2015-10-25 00:00:00 GMT
* 	 expire date: 2016-10-23 23:59:59 GMT
* 	 subjectAltName: www.binary.com matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
* 	 SSL certificate verify ok.
> GET /websockets/v3 HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Connection: Upgrade
> Upgrade: websocket
> Host: www.binary.com
> Origin: https://www.binary.com
>
< HTTP/1.1 503 Service Temporarily Unavailable
HTTP/1.1 503 Service Temporarily Unavailable
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
Server: cloudflare-nginx
< Date: Tue, 24 Nov 2015 01:14:53 GMT
Date: Tue, 24 Nov 2015 01:14:53 GMT
< Content-Type: text/html
Content-Type: text/html
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Connection: keep-alive
Connection: keep-alive
< Set-Cookie: __cfduid=dd9a3d193945c8fa93f30ada2e813f5c71448327693; expires=Wed, 23-Nov-16 01:14:53 GMT; path=/; domain=.binary.com; HttpOnly
Set-Cookie: __cfduid=dd9a3d193945c8fa93f30ada2e813f5c71448327693; expires=Wed, 23-Nov-16 01:14:53 GMT; path=/; domain=.binary.com; HttpOnly
< Strict-Transport-Security: max-age=15552000; preload
Strict-Transport-Security: max-age=15552000; preload
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< CF-RAY: 24a14274f5453506-LHR
CF-RAY: 24a14274f5453506-LHR

<
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
* Connection #0 to host www.binary.com left intact
```

This command only works intermittently and can establish a websocket connection

**Comment by Amsori** [comment] 2015-11-24 01:20
Still 503 http connection error.. :(

**Comment by davebond** [comment] 2015-11-24 01:23
The issue appears to be caused by cloudflare, I am in the UK, I've connected to a VPN in France which has changed the cloudflare endpoint, I now have a 100% success rate

**Comment by teo-binary** [comment] 2015-11-24 03:37
@Amsori We've relaxed our rate limit at higher rate now. Can you try again and see if you are still encountering the HTTP 503 issue? Thanks

**Comment by Amsori** [comment] 2015-11-24 04:08
@teo-binary still error . http://prntscr.com/969fjk

**Comment by teo-binary** [comment] 2015-11-24 07:57
@Amsori  can you provide me your current public IP and also retry again? I'll check again to see why you keep getting 503. Thanks

**Comment by Amsori** [comment] 2015-11-24 11:33
my ip is 36.74.24.123

**Comment by Amsori** [comment] 2015-11-24 11:33
36.74.24.123/24

On Tue, Nov 24, 2015 at 6:33 PM, Pangeran Mustika Biru <aam.amsori@gmail.com

**Comment by teo-binary** [comment] 2015-11-25 02:59
Hi @Amsori  , we've again increased the threshold of our ratelimit. Is your IP address still the same? We're monitoring the logs to see if your IP hits our limit

**Comment by teo-binary** [comment] 2015-11-26 02:44
Hi @Amsori can you confirm that the issue is resolved? I saw your IP address in our access log and appears to be fine now

**Comment by Amsori** [comment] 2015-11-26 03:42
We have still error 503 Temporary Service Unavailable
[image: Inline image 1]

**Comment by teo-binary** [comment] 2015-11-26 04:00
@Amsori  I saw successful login for yesterday from 36.74.24.123 for the following logins without any HTTP 503. Can you verify if your IP is the same? Also I'm unable to view the inline image in your previous reply.

- CR166154
- VRTC1204103
- VRTC1204188

**Comment by Amsori** [comment] 2015-11-26 04:06
if connect from website binary.com we can login, but still have found error
in logs website.

[image: Inline image 1]

and if we connect from application (my visual studio project) we still have
error message 503 if we try connect to web binary.com socket server.
my ip address is 36.74.24.123

Regards.

**Comment by teo-binary** [comment] 2015-11-26 04:09
visual studio project? Did your application go through some kind of proxy that causes it to show different IP to our server? Cause I can't find any HTTP 503 error at all for this IP 36.74.24.123

Which user account did your VS project login as?

**Comment by teo-binary** [comment] 2015-11-26 04:10
Can you upload those screenshots to http://imgur.com and share the link? I can't view any of the image you attached to the post

**Comment by raunakkathuria** [comment] 2016-01-04 07:32
this has been fixed. Closing the issue, feel free to open it if you still get the error

**Closed by raunakkathuria** 2016-01-04 07:32 UTC
